"""Demo seed data for the hospital admin dashboard.

Only inserted when the corresponding tables are empty so it is safe to
run on every startup.
"""

from src.modules.hospital.hospital_query import DEFAULT_SETTINGS

SEED_BEDS = [
    {
        "bed_id": "ICU-101",
        "ward": "ICU",
        "status": "OCCUPIED",
        "price": 850,
        "floor": 1,
        "assigned_nurse": "Nurse Sarah Jenkins",
        "equipment": '["Ventilator", "Cardiac Monitor", "Oxygen Infusion"]',
        "patient": "Robert Downey Jr.",
    },
    {
        "bed_id": "ICU-102",
        "ward": "ICU",
        "status": "AVAILABLE",
        "price": 850,
        "floor": 1,
        "assigned_nurse": "Nurse Sarah Jenkins",
        "equipment": '["Ventilator", "Cardiac Monitor", "Defibrillator"]',
        "patient": None,
    },
    {
        "bed_id": "ER-201",
        "ward": "Emergency",
        "status": "OCCUPIED",
        "price": 400,
        "floor": 2,
        "assigned_nurse": "Nurse David Vance",
        "equipment": '["Oxygen Port", "IV Stand", "Suction Unit"]',
        "patient": "Liam Neeson",
    },
    {
        "bed_id": "ER-202",
        "ward": "Emergency",
        "status": "SANITIZING",
        "price": 400,
        "floor": 2,
        "assigned_nurse": "Nurse David Vance",
        "equipment": '["Oxygen Port", "IV Stand"]',
        "patient": None,
    },
    {
        "bed_id": "GEN-301",
        "ward": "General Ward",
        "status": "OCCUPIED",
        "price": 150,
        "floor": 3,
        "assigned_nurse": "Nurse Maria Gomez",
        "equipment": '["IV Stand", "Calling Button"]',
        "patient": "Emma Watson",
    },
    {
        "bed_id": "GEN-302",
        "ward": "General Ward",
        "status": "AVAILABLE",
        "price": 150,
        "floor": 3,
        "assigned_nurse": "Nurse Maria Gomez",
        "equipment": '["IV Stand", "Calling Button"]',
        "patient": None,
    },
    {
        "bed_id": "GEN-303",
        "ward": "General Ward",
        "status": "RESERVED",
        "price": 150,
        "floor": 3,
        "assigned_nurse": "Nurse Maria Gomez",
        "equipment": '["IV Stand", "Telemetry Hookup"]',
        "patient": None,
    },
    {
        "bed_id": "PED-401",
        "ward": "Pediatrics",
        "status": "OCCUPIED",
        "price": 200,
        "floor": 4,
        "assigned_nurse": "Nurse John Doe",
        "equipment": '["Oxygen Port", "Pediatric Pulse-Ox"]',
        "patient": "Tommy Watson",
    },
    {
        "bed_id": "PED-402",
        "ward": "Pediatrics",
        "status": "AVAILABLE",
        "price": 200,
        "floor": 4,
        "assigned_nurse": "Nurse John Doe",
        "equipment": '["Oxygen Port"]',
        "patient": None,
    },
    {
        "bed_id": "MAT-501",
        "ward": "Maternity",
        "status": "OCCUPIED",
        "price": 300,
        "floor": 5,
        "assigned_nurse": "Nurse Sarah Jenkins",
        "equipment": '["Fetal Monitor", "Neonatal Warmer"]',
        "patient": "Scarlett Johansson",
    },
]

SEED_ADMISSIONS = [
    {
        "admission_id": "ADM-8392",
        "patient_name": "Emma Watson",
        "patient_age": 32,
        "patient_gender": "Female",
        "ward_type": "General Ward",
        "bed_id": "GEN-301",
        "admit_date": "2026-07-15",
        "discharge_date": "2026-07-22",
        "billing_amount": 1050,
        "status": "ADMITTED",
        "insurance_status": "COVERED",
        "patient_email": "emma.watson@gmail.com",
        "patient_phone": "+1 (555) 019-2834",
    },
    {
        "admission_id": "ADM-9481",
        "patient_name": "Liam Neeson",
        "patient_age": 68,
        "patient_gender": "Male",
        "ward_type": "Emergency",
        "bed_id": "ER-201",
        "admit_date": "2026-07-19",
        "discharge_date": "2026-07-24",
        "billing_amount": 2000,
        "status": "ADMITTED",
        "insurance_status": "PENDING",
        "patient_email": "liam@taken.com",
        "patient_phone": "+44 7911 123456",
    },
    {
        "admission_id": "ADM-4829",
        "patient_name": "Scarlett Johansson",
        "patient_age": 36,
        "patient_gender": "Female",
        "ward_type": "Maternity",
        "bed_id": "MAT-501",
        "admit_date": "2026-07-18",
        "discharge_date": "2026-07-25",
        "billing_amount": 2100,
        "status": "ADMITTED",
        "insurance_status": "COVERED",
        "patient_email": "scarlett@avengers.org",
        "patient_phone": "+1 (555) 102-8822",
    },
    {
        "admission_id": "ADM-1049",
        "patient_name": "Robert Downey Jr.",
        "patient_age": 55,
        "patient_gender": "Male",
        "ward_type": "ICU",
        "bed_id": "ICU-101",
        "admit_date": "2026-07-17",
        "discharge_date": "2026-07-21",
        "billing_amount": 3400,
        "status": "ADMITTED",
        "insurance_status": "COVERED",
        "patient_email": "rdj@stark.com",
        "patient_phone": "+1 (555) 300-3000",
    },
    {
        "admission_id": "ADM-1102",
        "patient_name": "Leonardo DiCaprio",
        "patient_age": 47,
        "patient_gender": "Male",
        "ward_type": "ICU",
        "bed_id": "ICU-102",
        "admit_date": "2026-07-21",
        "discharge_date": "2026-07-28",
        "billing_amount": 5950,
        "status": "SCHEDULED",
        "insurance_status": "UNINSURED",
        "patient_email": "leo@di-caprio.com",
        "patient_phone": "+1 (555) 987-6543",
    },
    {
        "admission_id": "ADM-5819",
        "patient_name": "Brad Pitt",
        "patient_age": 56,
        "patient_gender": "Male",
        "ward_type": "General Ward",
        "bed_id": "GEN-302",
        "admit_date": "2026-07-10",
        "discharge_date": "2026-07-14",
        "billing_amount": 600,
        "status": "DISCHARGED",
        "insurance_status": "COVERED",
        "patient_email": "pitt@brad.net",
        "patient_phone": "+1 (555) 321-7654",
    },
    {
        "admission_id": "ADM-9901",
        "patient_name": "Will Smith",
        "patient_age": 52,
        "patient_gender": "Male",
        "ward_type": "Emergency",
        "bed_id": "ER-202",
        "admit_date": "2026-07-12",
        "discharge_date": "2026-07-13",
        "billing_amount": 400,
        "status": "CANCELLED",
        "insurance_status": "UNINSURED",
        "patient_email": "freshprince@will.com",
        "patient_phone": "+1 (555) 111-2222",
    },
]

SEED_TASKS = [
    {
        "task_id": "TSK-8812",
        "bed_id": "ICU-101",
        "task_description": "Administer 10ml Epinephrine and monitor blood pressure",
        "priority": "EMERGENCY",
        "assigned_to": "Nurse Sarah Jenkins",
        "status": "IN-PROGRESS",
        "task_type": "NURSING",
        "timestamp": "10:30 AM",
    },
    {
        "task_id": "TSK-8813",
        "bed_id": "MAT-501",
        "task_description": "Deliver prescribed post-natal antibiotics from pharmacy",
        "priority": "HIGH",
        "assigned_to": "Nurse Sarah Jenkins",
        "status": "PENDING",
        "task_type": "PHARMACY",
        "timestamp": "12:15 PM",
    },
    {
        "task_id": "TSK-8814",
        "bed_id": "ER-202",
        "task_description": "Sanitize bed post discharge and replace sheets",
        "priority": "MEDIUM",
        "assigned_to": "Nurse David Vance",
        "status": "PENDING",
        "task_type": "SANITIZATION",
        "timestamp": "11:45 AM",
    },
    {
        "task_id": "TSK-8815",
        "bed_id": "GEN-301",
        "task_description": "Collect blood samples for comprehensive CBC and glucose test",
        "priority": "HIGH",
        "assigned_to": "Nurse Maria Gomez",
        "status": "COMPLETED",
        "task_type": "LAB-TEST",
        "timestamp": "08:15 AM",
    },
    {
        "task_id": "TSK-8816",
        "bed_id": "PED-401",
        "task_description": "Administer saline nebulizer",
        "priority": "LOW",
        "assigned_to": "Nurse John Doe",
        "status": "COMPLETED",
        "task_type": "NURSING",
        "timestamp": "09:30 AM",
    },
]
